server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka

management:
  tracing:
    sampling:
      probability: 1.0


spring:
  datasource:
    url: jdbc:mysql://localhost:8500/Customer
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
